#!/usr/bin/env bash
set -e

CIDIR=$(cd ${0%/*} && pwd)

pip install -r "${CIDIR}/requirements.txt" -r "${CIDIR}/requirements-dev.txt"
pep8 "${CIDIR}/avakas"
pylint --rcfile "${CIDIR}/.pylintrc" "${CIDIR}/avakas"
