[tox]
envlist = clean,py312,py310

[testenv]
setenv =
  TERM = dumb
  PATH = {env:PATH}
deps =
    -rrequirements.txt
    -rrequirements-dev.txt
commands = {toxinidir}/scripts/integration
distshare = {toxinidir}/.tox/builds
allowlist_externals =
    /tmp/avakas/scripts/integration

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase
