#!/usr/bin/env python

import sys
from random import randint
from lorem_text import lorem

def main(path):
    """Dat entrypoint tho"""
    paragraphs = randint(1, 5)
    words = lorem.paragraphs(paragraphs)
    with open(path, 'w') as fp:
        fp.write(words)
    exit(0)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        exit(1)
    main(sys.argv[1])
