#!/usr/bin/env python

import sys
from random import randint
from loremipsum import generate_paragraph

def main(path):
    """Dat entrypoint tho"""
    paragraphs = randint(0, 5)
    words = ''
    i = 0
    while i <= paragraphs:
        paragraph = generate_paragraph()[2]
        words += paragraph
        i += 1
    fp = open(path, 'w')
    fp.write(words)
    fp.close
    exit(0)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        exit(1)
    main(sys.argv[1])
