#!/usr/bin/env bash

# prudence above all else
set -e

# always know where your towel is
SCRIPT_DIR=$(cd "${0%/*}" && pwd)
export CIDIR="${SCRIPT_DIR%/*}"

# constant presence
BATSGIT="${CIDIR}/.bats-git"
BATSBIN="${CIDIR}/.bats"

if [ ! -d "$BATSGIT" ] ; then
    git clone --depth 1 https://github.com/sstephenson/bats.git "$BATSGIT"
fi
if [ ! -d "$BATSBIN" ] ; then
    cd "$BATSGIT"
    ./install.sh "$BATSBIN"
fi

if [ -z "$TRAVIS" ] ; then
    . "${CIDIR}/.ci-env/bin/activate"
fi
# integration tests
"${CIDIR}/.bats/bin/bats" "${CIDIR}"/tests/integration/*.bats
