#!/usr/bin/env bash

set -e
if [ "$BRANCH" != "master" ] ; then
    VSN=$(./avakas show . --pre-build 2> /dev/null)
else
    VSN=$(./avakas show . 2> /dev/null)
fi
[ ! -z "$VSN" ]
docker build -t "otakup0pe/avakas:${VSN}" .
docker push  "otakup0pe/avakas:${VSN}"
if [ "$BRANCH" == "master" ] ; then
    docker tag "otakup0pe/avakas:latest"
    docker push "otakup0pe/avakas:latest"
fi
