#!/usr/bin/env bash

set -e
if git describe --tags --exact-match HEAD &> /dev/null ; then
    LATEST="yes"
fi
if [ -z "$LATEST" ] ; then
    VSN=$(./avakas show . --pre-build 2> /dev/null)
else
    VSN=$(./avakas show . 2> /dev/null)
fi
[ ! -z "$VSN" ]
docker build \
       --build-arg "VERSION=${VSN}" \
       -t "otakup0pe/avakas:${VSN}" .
docker push  "otakup0pe/avakas:${VSN}"

if [ -n "$LATEST" ] ; then
    docker tag "otakup0pe/avakas:${VSN}" "otakup0pe/avakas:latest"
    docker push "otakup0pe/avakas:latest"
fi
