#!/usr/bin/env sh
set -e

SSH_KEY="/avakas-key"
AVAKAS="/opt/avakas/bin/avakas"

problems() {
    echo "Error: ${1}"
    exit 1
}

ACTION="$1"
if [ -z "$ACTION" ] ; then
    echo "avakas docker container ${VERSION}"
    "$AVAKAS" help
    exit 1
fi

ARGS="$*"
if [ "$ACTION" = "bump" ] || [ "$ACTION" = "set" ] ; then
    mkdir -p "${HOME}/.ssh"
    if [ -z "$SSH_AUTH_SOCK" ] ; then
        if [ ! -e "$SSH_KEY" ] ; then
            problems "SSH private key not found"
        else
	    if ! grep -q "PRIVATE KEY" "$SSH_KEY" ; then
		problems "SSH private key is corrupt"
	    fi
        fi
    fi
    ssh-keyscan "$SSH_SCAN_HOST" 2> /dev/null 1> "${HOME}/.ssh/known_hosts" || problems "Unable to load git host key"
    chmod -R og-rwx "${HOME}/.ssh"
fi

if [ -e "/etc/avakas/avakasrc" ] ; then
    # shellcheck disable=SC1091
    . /etc/avakas/avakasrc
fi
"$AVAKAS" $ARGS
