---
name: "release"

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "install testenv"
        run: "make testenv"
      - name: "install avakas to version itself"
        run: "make install"
      - name: "Get current version"
        run: avakas show . --flavor "git-native"
      - name: "Build a package"
        run: "make package"
      - name: "Publish to pypi"
        uses: "pypa/gh-action-pypi-publish@v1.3.1"
        with:
          user: "__token__"
          password: "${{ secrets.PYPI_TOKEN }}"
      - name: "Build and push docker bits"
        uses: "docker/build-push-action@v1"
        with:
          username: "${{ secrets.DOCKER_USER }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          repository: "otakup0pe/avakas"
          tag_with_ref: true
          tags: "latest"
